/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

extern "C" 
{
/*
 * Class:     JNITest
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_testing_jni_JNITest_helloWorld
  (JNIEnv *, jobject);
}