project(${TEA_PROJECT_NAME}Core)

set(BUILD_SHARED_LIBS ON CACHE BOOL "Build shared libraries" FORCE)
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

add_library(${TEA_PROJECT_NAME}Core 
    ${SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/Exports.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Exports.cpp    
    ${CMAKE_CURRENT_SOURCE_DIR}/DLLEntryPoint.cpp
)

target_include_directories(${TEA_PROJECT_NAME}Core PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

target_link_libraries(${TEA_PROJECT_NAME}Core PUBLIC ${DEPENDENCIES}
    BoilingHotWater
    TeaCup
    Tea
)

set_target_properties(${TEA_PROJECT_NAME}Core PROPERTIES 
    ARCHIVE_OUTPUT_DIRECTORY ${OUTPUT_DIR}
    LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY ${OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIR}
    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIR}
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIR}
)

install(TARGETS ${TEA_PROJECT_NAME}Core RUNTIME DESTINATION ${OUTPUT_DIR})