/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_testing_jni_JNITest
#define _Included_testing_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_testing_jni_JNITest_helloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif