project(glew)

find_package(OpenGL REQUIRED)

set(GLEW_INCLUDE_DIR ${GLEW_DIR}/include)
set(GLEW_LIB_DIR ${GLEW_DIR}/lib/Release/Win32)

file(GLOB_RECURSE GLEW_FILES ${GLEW_INCLUDE_DIR}/GL/*.h)

add_library(glew INTERFACE ${GLEW_FILES})

target_include_directories(glew INTERFACE 
    ${GLEW_INCLUDE_DIR}
)

#target_link_directories(glew PUBLIC 
#    ${GLEW_LIB_DIR}
#)

set_target_properties(glew PROPERTIES 
    #SUFFIX ".dll"
    #LINKER_LANGUAGE CXX
    ARCHIVE_OUTPUT_DIRECTORY ${DEPENDENCIES_OUTPUT_DIR}
    LIBRARY_OUTPUT_DIRECTORY ${DEPENDENCIES_OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY ${DEPENDENCIES_OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${DEPENDENCIES_OUTPUT_DIR}
    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${DEPENDENCIES_OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${DEPENDENCIES_OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${DEPENDENCIES_OUTPUT_DIR}
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${DEPENDENCIES_OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${DEPENDENCIES_OUTPUT_DIR}
)
message(STATUS "GLEW_INCLUDE_DIR: ${GLEW_INCLUDE_DIR}")