project(imgui)

file(GLOB IMGUI_SOURCES ${IMGUI_DIR}/*.cpp)
file(GLOB IMGUI_HEADERS ${IMGUI_DIR}/*.h)

set(IMGUI_BACKENDS_DIR ${IMGUI_DIR}/backends)

set(IMGUI_BACKEND_SOURCES
    ${IMGUI_BACKENDS_DIR}/imgui_impl_glfw.cpp
    ${IMGUI_BACKENDS_DIR}/imgui_impl_opengl3.cpp
    #${IMGUI_BACKENDS_DIR}/imgui_impl_vulkan.cpp
)
set(IMGUI_BACKEND_HEADERS
    ${IMGUI_BACKENDS_DIR}/imgui_impl_glfw.h
    ${IMGUI_BACKENDS_DIR}/imgui_impl_opengl3.h
    #${IMGUI_BACKENDS_DIR}/imgui_impl_vulkan.h
)

set(IMGUI_FILES
    ${IMGUI_SOURCES}
    ${IMGUI_HEADERS}
    
    ${IMGUI_BACKEND_SOURCES}
    ${IMGUI_BACKEND_HEADERS}
)

set(IMGUI_INCLUDE_DIRS
    ${IMGUI_DIR}
    ${IMGUI_BACKENDS_DIR}
)

add_library(imgui STATIC ${IMGUI_FILES})

target_include_directories(imgui PUBLIC ${IMGUI_INCLUDE_DIRS})
target_link_libraries(imgui PUBLIC glfw)

set_target_properties(imgui PROPERTIES 
    #SUFFIX ".dll"
    #LINKER_LANGUAGE CXX
    ARCHIVE_OUTPUT_DIRECTORY ${DEPENDENCIES_OUTPUT_DIR}
    LIBRARY_OUTPUT_DIRECTORY ${DEPENDENCIES_OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY ${DEPENDENCIES_OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${DEPENDENCIES_OUTPUT_DIR}
    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${DEPENDENCIES_OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${DEPENDENCIES_OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${DEPENDENCIES_OUTPUT_DIR}
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${DEPENDENCIES_OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${DEPENDENCIES_OUTPUT_DIR}
)